# Generated by Django 5.1 on 2024-08-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sellong_price', models.FloatField()),
                ('dicounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CR', 'curd'), ('CZ', 'Cheese'), ('MS', 'Milkshake'), ('PN', 'Paneer'), ('LS', 'Lassi'), ('ML', 'Milk'), ('GH', 'Ghee'), ('IC', 'Ice-Cream')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
